-- =====================================================
-- PROYECTO: EcoMarket S.A.
-- AVANCE – BASE DE DATOS Y ESTRUCTURAS PL/SQL
-- Autor: Daniel Rodríguez y grupo
-- =====================================================

-- =====================================================
--  CREACIÓN DE TABLAS
-- =====================================================

CREATE TABLE categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE proveedor (
    id_proveedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(20)
);

CREATE TABLE producto (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(10) UNIQUE,
    nombre VARCHAR2(100),
    precio NUMBER(10,2),
    stock NUMBER,
    id_categoria NUMBER REFERENCES categoria(id_categoria),
    id_proveedor NUMBER REFERENCES proveedor(id_proveedor)
);

CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    correo VARCHAR2(100)
);

CREATE TABLE venta (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE DEFAULT SYSDATE,
    id_cliente NUMBER REFERENCES cliente(id_cliente),
    total NUMBER(10,2)
);

CREATE TABLE detalle_venta (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta NUMBER REFERENCES venta(id_venta),
    id_producto NUMBER REFERENCES producto(id_producto),
    cantidad NUMBER,
    subtotal NUMBER(10,2)
);

CREATE TABLE auditoria (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR2(50),
    accion VARCHAR2(50),
    fecha DATE DEFAULT SYSDATE,
    usuario VARCHAR2(50)
);

-- =====================================================
-- INSERCIÓN DE DATOS BASE
-- =====================================================

INSERT INTO categoria (nombre) VALUES ('Bebidas');
INSERT INTO categoria (nombre) VALUES ('Snacks');
INSERT INTO proveedor (nombre, telefono) VALUES ('Distribuidora CR', '8888-8888');
INSERT INTO proveedor (nombre, telefono) VALUES ('Alimentos Tico', '2277-5544');

COMMIT;

-- =====================================================
-- VISTAS (5 de 10 programadas)
-- =====================================================

CREATE OR REPLACE VIEW vw_productos_disponibles AS
SELECT p.nombre, p.precio, p.stock, c.nombre AS categoria
FROM producto p
JOIN categoria c ON p.id_categoria = c.id_categoria;

CREATE OR REPLACE VIEW vw_clientes_con_ventas AS
SELECT c.nombre, COUNT(v.id_venta) AS total_ventas
FROM cliente c LEFT JOIN venta v ON c.id_cliente = v.id_cliente
GROUP BY c.nombre;

CREATE OR REPLACE VIEW vw_detalle_ventas AS
SELECT v.id_venta, c.nombre AS cliente, p.nombre AS producto, d.cantidad, d.subtotal
FROM venta v
JOIN cliente c ON v.id_cliente = c.id_cliente
JOIN detalle_venta d ON v.id_venta = d.id_venta
JOIN producto p ON d.id_producto = p.id_producto;

CREATE OR REPLACE VIEW vw_top_productos AS
SELECT p.nombre, SUM(d.cantidad) AS vendidos
FROM detalle_venta d JOIN producto p ON d.id_producto = p.id_producto
GROUP BY p.nombre
ORDER BY vendidos DESC;

CREATE OR REPLACE VIEW vw_stock_bajo AS
SELECT nombre, stock FROM producto WHERE stock < 10;

-- =====================================================
-- FUNCIONES (5 de 15 programadas)
-- =====================================================

CREATE OR REPLACE FUNCTION fn_total_venta(p_id NUMBER) RETURN NUMBER IS
    v_total NUMBER;
BEGIN
    SELECT SUM(subtotal) INTO v_total
    FROM detalle_venta
    WHERE id_venta = p_id;
    RETURN NVL(v_total,0);
END;
/

CREATE OR REPLACE FUNCTION fn_stock_disponible(p_id NUMBER) RETURN NUMBER IS
    v_stock NUMBER;
BEGIN
    SELECT stock INTO v_stock FROM producto WHERE id_producto = p_id;
    RETURN NVL(v_stock,0);
END;
/

CREATE OR REPLACE FUNCTION fn_precio_promedio RETURN NUMBER IS
    v_prom NUMBER;
BEGIN
    SELECT AVG(precio) INTO v_prom FROM producto;
    RETURN NVL(v_prom,0);
END;
/

CREATE OR REPLACE FUNCTION fn_contar_clientes RETURN NUMBER IS
    v_cant NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cant FROM cliente;
    RETURN v_cant;
END;
/

CREATE OR REPLACE FUNCTION fn_ventas_por_cliente(p_id_cliente NUMBER) RETURN NUMBER IS
    v_cant NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cant FROM venta WHERE id_cliente = p_id_cliente;
    RETURN v_cant;
END;
/

-- =====================================================
-- PROCEDIMIENTOS (10 de 25 programados)
-- =====================================================

CREATE OR REPLACE PROCEDURE crear_producto(
    p_codigo VARCHAR2,
    p_nombre VARCHAR2,
    p_precio NUMBER,
    p_stock NUMBER,
    p_id_categoria NUMBER,
    p_id_proveedor NUMBER
) AS
BEGIN
    INSERT INTO producto (codigo, nombre, precio, stock, id_categoria, id_proveedor)
    VALUES (p_codigo, p_nombre, p_precio, p_stock, p_id_categoria, p_id_proveedor);
END;
/

CREATE OR REPLACE PROCEDURE actualizar_producto(
    p_id NUMBER,
    p_nombre VARCHAR2,
    p_precio NUMBER,
    p_stock NUMBER
) AS
BEGIN
    UPDATE producto
    SET nombre = p_nombre, precio = p_precio, stock = p_stock
    WHERE id_producto = p_id;
END;
/

CREATE OR REPLACE PROCEDURE eliminar_producto(p_id NUMBER) AS
BEGIN
    DELETE FROM producto WHERE id_producto = p_id;
END;
/

CREATE OR REPLACE PROCEDURE crear_cliente(p_nombre VARCHAR2, p_correo VARCHAR2) AS
BEGIN
    INSERT INTO cliente (nombre, correo) VALUES (p_nombre, p_correo);
END;
/

CREATE OR REPLACE PROCEDURE crear_venta(p_id_cliente NUMBER) AS
BEGIN
    INSERT INTO venta (id_cliente, total) VALUES (p_id_cliente, 0);
END;
/

CREATE OR REPLACE PROCEDURE agregar_detalle(
    p_id_venta NUMBER,
    p_id_producto NUMBER,
    p_cantidad NUMBER
) AS
    v_precio NUMBER;
BEGIN
    SELECT precio INTO v_precio FROM producto WHERE id_producto = p_id_producto;
    INSERT INTO detalle_venta (id_venta, id_producto, cantidad, subtotal)
    VALUES (p_id_venta, p_id_producto, p_cantidad, v_precio * p_cantidad);
    UPDATE venta SET total = fn_total_venta(p_id_venta) WHERE id_venta = p_id_venta;
END;
/

CREATE OR REPLACE PROCEDURE eliminar_cliente(p_id_cliente NUMBER) AS
BEGIN
    DELETE FROM cliente WHERE id_cliente = p_id_cliente;
END;
/

CREATE OR REPLACE PROCEDURE listar_productos IS
BEGIN
    FOR r IN (SELECT nombre, precio, stock FROM producto) LOOP
        DBMS_OUTPUT.PUT_LINE(r.nombre || ' - ' || r.precio || ' (' || r.stock || ')');
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE listar_clientes IS
BEGIN
    FOR r IN (SELECT * FROM cliente) LOOP
        DBMS_OUTPUT.PUT_LINE(r.id_cliente || ' - ' || r.nombre);
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE auditar(p_tabla VARCHAR2, p_accion VARCHAR2) AS
BEGIN
    INSERT INTO auditoria (tabla_afectada, accion, usuario)
    VALUES (p_tabla, p_accion, USER);
END;
/

-- =====================================================
-- PAQUETES (3 de 10 programados)
-- =====================================================

CREATE OR REPLACE PACKAGE pkg_productos AS
    PROCEDURE listar;
    PROCEDURE actualizar_stock(p_id_producto NUMBER, p_cantidad NUMBER);
END pkg_productos;
/

CREATE OR REPLACE PACKAGE BODY pkg_productos AS
    PROCEDURE listar AS
    BEGIN
        FOR r IN (SELECT nombre, precio FROM producto) LOOP
            DBMS_OUTPUT.PUT_LINE(r.nombre || ' ₡' || r.precio);
        END LOOP;
    END;

    PROCEDURE actualizar_stock(p_id_producto NUMBER, p_cantidad NUMBER) AS
    BEGIN
        UPDATE producto SET stock = stock - p_cantidad WHERE id_producto = p_id_producto;
    END;
END pkg_productos;
/

CREATE OR REPLACE PACKAGE pkg_clientes AS
    PROCEDURE listar;
    FUNCTION total_clientes RETURN NUMBER;
END pkg_clientes;
/

CREATE OR REPLACE PACKAGE BODY pkg_clientes AS
    PROCEDURE listar AS
    BEGIN
        FOR r IN (SELECT * FROM cliente) LOOP
            DBMS_OUTPUT.PUT_LINE(r.id_cliente || ' - ' || r.nombre);
        END LOOP;
    END;

    FUNCTION total_clientes RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_total FROM cliente;
        RETURN v_total;
    END;
END pkg_clientes;
/

-- =====================================================
-- 7️⃣ TRIGGERS (2 de 5 programados)
-- =====================================================

CREATE OR REPLACE TRIGGER trg_auditoria_producto
AFTER INSERT OR UPDATE OR DELETE ON producto
FOR EACH ROW
BEGIN
    INSERT INTO auditoria (tabla_afectada, accion, usuario)
    VALUES ('PRODUCTO', 'CAMBIO', USER);
END;
/

CREATE OR REPLACE TRIGGER trg_actualiza_total
AFTER INSERT OR DELETE OR UPDATE ON detalle_venta
FOR EACH ROW
BEGIN
    UPDATE venta
    SET total = fn_total_venta(:NEW.id_venta)
    WHERE id_venta = :NEW.id_venta;
END;
/

-- =====================================================
-- CURSORES (5 de 15 programados)
-- =====================================================

DECLARE
    CURSOR cur_productos IS SELECT nombre, precio FROM producto;
    v_nombre producto.nombre%TYPE;
    v_precio producto.precio%TYPE;
BEGIN
    OPEN cur_productos;
    LOOP
        FETCH cur_productos INTO v_nombre, v_precio;
        EXIT WHEN cur_productos%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Producto: ' || v_nombre || ' - ₡' || v_precio);
    END LOOP;
    CLOSE cur_productos;
END;
/

DECLARE
    CURSOR cur_clientes IS SELECT nombre, correo FROM cliente;
    v_nombre cliente.nombre%TYPE;
    v_correo cliente.correo%TYPE;
BEGIN
    OPEN cur_clientes;
    LOOP
        FETCH cur_clientes INTO v_nombre, v_correo;
        EXIT WHEN cur_clientes%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Cliente: ' || v_nombre || ' (' || v_correo || ')');
    END LOOP;
    CLOSE cur_clientes;
END;
/

-- =====================================================
-- FIN DEL AVANCE 2
-- =====================================================

COMMIT;
PROMPT '✅ Avance 2 ejecutado correctamente';

